### ISSUE TITLE
Uncaught TypeError: CompletionManager is not a function

### ISSUE THREAD

**Issue by mlxd** [msiniscalchi/atom-latextools#95]
When I open a .tex file I receive the following uncaught exception. This has only been a problem since I updated to 0.8.1 today.

1. Open *.tex file

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.1

### Stack Trace

Uncaught TypeError: CompletionManager is not a function

```
At /Users/mlxd/.atom/packages/latextools/lib/latextools.coffee:315

TypeError: CompletionManager is not a function
    at Object.module.exports.Latextools.requireIfNeeded (/Users/mlxd/.atom/packages/latextools/lib/latextools.coffee:315:13)
    at /Users/mlxd/.atom/packages/latextools/lib/latextools.coffee:272:62
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```

### Commands

```
     -0:45.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "latex-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex, v0.32.0
latexer, v0.3.0
latextools, v0.8.1
pdf-view, v0.50.0

# Dev
No dev packages
```

**Comment by ig0774** [comment]
Could you try uninstalling and reinstalling the package? It looks like either something went wrong with the upgrade or for some other reason your `lib/latextools.coffee` file does not match v0.8.1.

The line numbers in the stack trace don't correspond to v0.8.1's [`latextools.coffee`](https://github.com/msiniscalchi/atom-latextools/blob/396c2254b945a06c198d641e8cf13bc8c7affd35/lib/latextools.coffee), nor with any other release I can find. In particular, line [315](https://github.com/msiniscalchi/atom-latextools/blob/396c2254b945a06c198d641e8cf13bc8c7affd35/lib/latextools.coffee#L315) (where the error is raised) is `switch process.platform`. You most likely have at your lines 314–315:

```coffee
CompletionManager ?= require './completion-manager'
@completionManager ?= new CompletionManager(@ltConsole)
```

Which is code that was used prior to v0.8.1, but was changed in v0.8.1 to [this](https://github.com/msiniscalchi/atom-latextools/blob/396c2254b945a06c198d641e8cf13bc8c7affd35/lib/latextools.coffee#L335).

Similarly, line [272](https://github.com/msiniscalchi/atom-latextools/blob/396c2254b945a06c198d641e8cf13bc8c7affd35/lib/latextools.coffee#272) which, in the stack trace appears to be invoking `requireIfNeeded` is, in fact, an innocuous event definition. The fact that your line 272 is invoked from event-kit probably means it was part of the [`atom.workspace.observeTextEditors`](https://github.com/msiniscalchi/atom-latextools/blob/25a613f921f0d4046d9de5057e7d216eef9a89d9/lib/latextools.coffee#L272) handler that was eliminated in v0.8.1. Your line 272 appears to correspond to v0.8.0's [line 279](https://github.com/msiniscalchi/atom-latextools/blob/25a613f921f0d4046d9de5057e7d216eef9a89d9/lib/latextools.coffee#L279).

**Comment by mlxd** [comment]
An uninstall and reinstall fixed it for me. Upgrades worked fine across my other machines, so this was probably just an isolated event. Thanks for the help.
